<?php

namespace Database\Seeders;

use App\Models\AuditSecuriteRapport;
use App\Models\AuditSecuriteVulnerabilite;
use Illuminate\Database\Seeder;

class AuditSecuriteSeeder extends Seeder
{
    public function run(): void
    {
        $rapport = AuditSecuriteRapport::create([
            'titre'      => 'Audit de sécurité initial — E-BEB Finance v1.0',
            'version'    => '1.0',
            'statut'     => 'TERMINE',
            'notes'      => 'Audit complet de la plateforme couvrant Backend (Laravel 11), Frontend (React/TanStack), API REST, base de données et configurations.',
            'date_audit' => now(),
        ]);

        $vulnerabilites = [

            // ──────────── CRITIQUE ────────────
            [
                'code'           => 'SEC-001',
                'titre'          => 'Code OTP retourné en clair dans les réponses API',
                'criticite'      => 'CRITIQUE',
                'statut'         => 'CORRIGE',
                'categorie'      => 'Authentification',
                'description'    => 'Les méthodes inscription() et connexion() de AuthController incluaient le code OTP dans le corps de la réponse JSON via $data[\'otp\'] = $otp. OtpService::generateAndSend() retournait \'code_otp\' => $code dans son tableau de retour. Cela permettait à tout client API de lire le code OTP sans accès à l\'email.',
                'impact'         => 'Contournement total de l\'authentification à deux facteurs. Un attaquant peut inscrire un utilisateur, récupérer l\'OTP depuis la réponse et valider le compte sans accès à l\'email. CRITIQUE car cela compromet tous les comptes utilisateurs.',
                'recommandation' => 'Supprimer \'code_otp\' du tableau de retour de OtpService::generateAndSend(). Ne jamais inclure de secrets dans les réponses API. L\'OTP doit être transmis uniquement par le canal sécurisé (email/SMS).',
                'fichier'        => 'app/Http/Controllers/Apiv1/AuthController.php + app/Services/OtpService.php',
                'ligne'          => '53, 154 (AuthController) / 55 (OtpService)',
                'date_correction' => now(),
                'notes_correction' => 'Corrigé : code_otp retiré du retour de OtpService::generateAndSend(). Les réponses API n\'exposent plus que success et message.',
            ],
            [
                'code'           => 'SEC-002',
                'titre'          => 'Validation automatique KYC sans contrôle administrateur',
                'criticite'      => 'CRITIQUE',
                'statut'         => 'CORRIGE',
                'categorie'      => 'Contrôle d\'accès / Logique métier',
                'description'    => 'DocumentService::modifierDocument() et ajouterDocument() validaient automatiquement les documents KYC (statut → VALIDE) et activaient les comptes utilisateurs (statut → ACTIF) dès que tous les champs requis étaient remplis, sans aucune intervention d\'un administrateur.',
                'impact'         => 'N\'importe quel utilisateur pouvait remplir des documents KYC falsifiés, les voir automatiquement validés, et accéder à toutes les fonctionnalités financières sans vérification humaine. Fraude documentaire facilitée.',
                'recommandation' => 'La validation KYC doit être une action manuelle exclusive des administrateurs via DocumentService::modifierStatutDocument(). Les documents soumis doivent rester en statut EN_ATTENTE jusqu\'à revue explicite.',
                'fichier'        => 'app/Services/DocumentService.php',
                'ligne'          => '333-352 (modifierDocument) / 480-498 (ajouterDocument)',
                'date_correction' => now(),
                'notes_correction' => 'Corrigé : logique d\'auto-validation supprimée. Les documents restent EN_ATTENTE après soumission.',
            ],
            [
                'code'           => 'SEC-003',
                'titre'          => 'Tokens Sanctum sans expiration',
                'criticite'      => 'CRITIQUE',
                'statut'         => 'CORRIGE',
                'categorie'      => 'Gestion des sessions / Tokens',
                'description'    => 'config/sanctum.php avait \'expiration\' => null, ce qui signifie que les tokens API générés lors de la connexion ne expiraient jamais. Un token volé donnait un accès permanent à toutes les données financières de l\'utilisateur.',
                'impact'         => 'Vol de session permanent. Accès aux données financières, opérations bancaires, KYC sans limite de temps. Impossible de forcer la re-authentification périodique.',
                'recommandation' => 'Configurer \'expiration\' => 10080 (7 jours) ou une valeur adaptée au modèle de sécurité. Implémenter un mécanisme de refresh token pour les sessions longues.',
                'fichier'        => 'config/sanctum.php',
                'ligne'          => '53',
                'date_correction' => now(),
                'notes_correction' => 'Corrigé : expiration fixée à 10080 minutes (7 jours) via env SANCTUM_TOKEN_EXPIRATION.',
            ],
            [
                'code'           => 'SEC-004',
                'titre'          => 'Calculs financiers en virgule flottante (float)',
                'criticite'      => 'CRITIQUE',
                'statut'         => 'DETECTE',
                'categorie'      => 'Précision financière',
                'description'    => 'Les modèles Cotisation, Operation, PortefeuilleEpargne et Reversement castent les montants en float PHP. Les flottants ont des erreurs de précision inhérentes (0.1 + 0.2 = 0.30000000000000004). PaiementService.php effectue des calculs arithmétiques directs sur ces valeurs.',
                'impact'         => 'Erreurs d\'arrondi cumulatives sur les cotisations, reversements et commissions. Sur des milliers de transactions, ces erreurs peuvent représenter des pertes ou gains financiers injustifiés. Problème de conformité comptable.',
                'recommandation' => 'Utiliser des colonnes DECIMAL(15,2) en base de données. Utiliser BCMath (bcadd, bcmul, bcdiv) pour tous les calculs financiers. Changer les casts Eloquent de float à string et traiter avec BCMath.',
                'fichier'        => 'app/Models/Cotisation.php, Operation.php, PortefeuilleEpargne.php, Reversement.php / app/Services/PaiementService.php',
                'ligne'          => '20-22 (Cotisation) / 34 (Operation) / 18-26 (PortefeuilleEpargne)',
            ],

            // ──────────── ÉLEVÉ ────────────
            [
                'code'           => 'SEC-005',
                'titre'          => 'Aucune configuration CORS explicite',
                'criticite'      => 'ELEVE',
                'statut'         => 'CORRIGE',
                'categorie'      => 'Configuration serveur',
                'description'    => 'Aucun fichier config/cors.php n\'existait dans le projet. Laravel utilise alors des valeurs par défaut qui peuvent autoriser des origines non souhaitées à accéder à l\'API.',
                'impact'         => 'Attaques Cross-Origin : un site malveillant peut effectuer des requêtes API authentifiées au nom d\'un utilisateur connecté si le navigateur envoie les cookies/credentials.',
                'recommandation' => 'Créer config/cors.php avec la liste explicite des origines autorisées (domaine frontend production uniquement). Ne jamais utiliser \'*\' en production avec supports_credentials: true.',
                'fichier'        => 'config/cors.php',
                'ligne'          => 'N/A (fichier absent)',
                'date_correction' => now(),
                'notes_correction' => 'Corrigé : config/cors.php créé avec origines limitées via env CORS_ALLOWED_ORIGINS.',
            ],
            [
                'code'           => 'SEC-006',
                'titre'          => 'Absence de rate limiting sur les routes d\'authentification',
                'criticite'      => 'ELEVE',
                'statut'         => 'CORRIGE',
                'categorie'      => 'Protection contre les attaques',
                'description'    => 'Les routes /api/auth/* (inscription, connexion, OTP) et /administration/auth/se-connecter n\'avaient aucun middleware throttle. Un attaquant pouvait effectuer des milliers de tentatives de connexion ou d\'inscription par minute.',
                'impact'         => 'Attaques par force brute sur les codes PIN, brute-force sur les OTP (6 chiffres = 1M combinaisons), création massive de comptes fictifs, déni de service applicatif.',
                'recommandation' => 'Appliquer throttle:10,1 sur les routes d\'auth utilisateur et throttle:5,1 sur les routes admin. Ajouter throttle:3,1 spécifiquement sur le renvoi d\'OTP pour éviter l\'abus.',
                'fichier'        => 'routes/api.php',
                'ligne'          => '9-24, 103-105',
                'date_correction' => now(),
                'notes_correction' => 'Corrigé : throttle:10,1 sur routes auth utilisateur, throttle:5,1 sur admin, throttle:3,1 sur renvoi OTP.',
            ],
            [
                'code'           => 'SEC-007',
                'titre'          => 'Fichiers SVG autorisés dans les uploads (XSS via SVG)',
                'criticite'      => 'ELEVE',
                'statut'         => 'CORRIGE',
                'categorie'      => 'Upload de fichiers / XSS',
                'description'    => 'SaveParametreGeneralRequest autorisait les formats SVG pour logo_principal et logo_favicon. AjoutDocumentKYCRequest autorisait SVG et GIF pour les documents KYC (recto, verso, selfie). Les fichiers SVG peuvent contenir du JavaScript exécutable via balises <script> ou attributs d\'événements.',
                'impact'         => 'Un attaquant peut uploader un SVG malveillant contenant du JavaScript. Si ce fichier est servi sans Content-Type: image/svg+xml et sans CSP, le navigateur peut l\'exécuter, causant une attaque XSS stockée touchant les admins et utilisateurs.',
                'recommandation' => 'Retirer SVG et GIF de tous les validateurs de fichiers. Pour le logo (admins seulement), si SVG est nécessaire, sanitiser le fichier avec une bibliothèque SVG (ex: svg-sanitizer) et l\'interdire pour les documents KYC (uploads utilisateurs).',
                'fichier'        => 'app/Http/Requests/SaveParametreGeneralRequest.php, AjoutDocumentKYCRequest.php',
                'ligne'          => '30-31 (SaveParametreGeneralRequest) / 31-33 (AjoutDocumentKYCRequest)',
                'date_correction' => now(),
                'notes_correction' => 'Corrigé : SVG et GIF retirés des mimes autorisés. Logo principal et favicon : PNG/JPG/JPEG/WebP uniquement. Documents KYC : JPEG/PNG/JPG uniquement.',
            ],
            [
                'code'           => 'SEC-008',
                'titre'          => 'Tokens admin non révoqués lors de la désactivation de compte',
                'criticite'      => 'ELEVE',
                'statut'         => 'CORRIGE',
                'categorie'      => 'Gestion des sessions',
                'description'    => 'La méthode AdminGestionService::changerStatut() mettait à jour statut_compte = INACTIF mais ne révoquait pas les tokens Sanctum actifs de l\'administrateur. Un admin désactivé conservait un accès valide jusqu\'à expiration naturelle du token.',
                'impact'         => 'Un administrateur révoqué (pour faute, départ) peut continuer à accéder au panel d\'administration pendant jusqu\'à 7 jours. Accès aux données financières sensibles après départ.',
                'recommandation' => 'Appeler $admin->tokens()->delete() immédiatement lors de la désactivation. Faire de même lors de l\'archivage.',
                'fichier'        => 'app/Services/AdminGestionService.php',
                'ligne'          => '219-236',
                'date_correction' => now(),
                'notes_correction' => 'Corrigé : $admin->tokens()->delete() ajouté lors du passage à statut INACTIF.',
            ],
            [
                'code'           => 'SEC-009',
                'titre'          => 'Bloc catch vide dans connexion() — erreurs silencieuses',
                'criticite'      => 'ELEVE',
                'statut'         => 'CORRIGE',
                'categorie'      => 'Gestion des erreurs',
                'description'    => 'La méthode connexion() dans AuthController avait un catch vide (catch (\Throwable $th) { //throw $th; }). Toute exception levée lors de la connexion était silencieusement ignorée, retournant une réponse HTTP 200 vide au client.',
                'impact'         => 'Les erreurs de connexion (base de données inaccessible, service OTP en panne) sont cachées. Le client reçoit une réponse vide et peut croire que la connexion a fonctionné. Débogage impossible en production.',
                'recommandation' => 'Toujours retourner une réponse d\'erreur appropriée dans les blocs catch. Utiliser $this->throw($e) ou $this->sendError() systématiquement.',
                'fichier'        => 'app/Http/Controllers/Apiv1/AuthController.php',
                'ligne'          => '159-161',
                'date_correction' => now(),
                'notes_correction' => 'Corrigé : catch vide remplacé par return $this->throw($th) avec vérification du succès de l\'envoi OTP.',
            ],
            [
                'code'           => 'SEC-010',
                'titre'          => 'Race condition sur la vérification des doublons de paiement',
                'criticite'      => 'ELEVE',
                'statut'         => 'DETECTE',
                'categorie'      => 'Logique métier / Concurrence',
                'description'    => 'PaiementService::traiterPaiementEntrant() vérifie l\'unicité de reference_externe avec ->exists(), puis crée le paiement dans une opération distincte. Deux requêtes concurrentes avec la même référence peuvent toutes deux passer la vérification avant que l\'une n\'insère.',
                'impact'         => 'Double-paiement : la même transaction mobile money peut être enregistrée deux fois, créditant deux fois le compte de l\'utilisateur. Perte financière directe pour la plateforme.',
                'recommandation' => 'Envelopper la vérification et la création dans DB::transaction() avec PaiementEntrant::lockForUpdate(). Ou ajouter une contrainte UNIQUE sur reference_externe en base de données (qui rejette le doublon avec une exception catchable).',
                'fichier'        => 'app/Services/PaiementService.php',
                'ligne'          => '36-41',
            ],

            // ──────────── MOYEN ────────────
            [
                'code'           => 'SEC-011',
                'titre'          => 'Comparaison OTP non résistante aux attaques temporelles',
                'criticite'      => 'MOYEN',
                'statut'         => 'CORRIGE',
                'categorie'      => 'Cryptographie',
                'description'    => 'OtpService::verify() utilisait $otp->code_otp !== $code pour comparer le code soumis au code stocké. L\'opérateur !== est une comparaison de chaîne standard, potentiellement vulnérable aux attaques par canal auxiliaire temporel (timing attack).',
                'impact'         => 'Faible en pratique sur des codes OTP de 6 chiffres, mais un attaquant avec accès réseau local peut théoriquement mesurer les temps de réponse pour déduire des informations sur le code.',
                'recommandation' => 'Utiliser hash_equals((string)$otp->code_otp, (string)$code) pour une comparaison en temps constant.',
                'fichier'        => 'app/Services/OtpService.php',
                'ligne'          => '124',
                'date_correction' => now(),
                'notes_correction' => 'Corrigé : comparaison remplacée par hash_equals().',
            ],
            [
                'code'           => 'SEC-012',
                'titre'          => 'Méthode de debug OTP publique (getOtpInfo)',
                'criticite'      => 'MOYEN',
                'statut'         => 'CORRIGE',
                'categorie'      => 'Exposition d\'informations',
                'description'    => 'OtpService::getOtpInfo() était une méthode publique retournant toutes les informations de session OTP d\'un utilisateur, incluant le code en clair, le nombre de tentatives et la date d\'expiration. Elle était marquée "pour debug uniquement" mais aucune restriction ne l\'empêchait d\'être appelée depuis un contrôleur.',
                'impact'         => 'Si cette méthode était exposée via une route (directement ou par erreur), n\'importe qui connaissant un numéro de téléphone pouvait récupérer le code OTP actif de cet utilisateur.',
                'recommandation' => 'Supprimer toute méthode de debug en production. Si nécessaire pour les tests, la limiter aux environnements non-production via app()->environment(\'local\').',
                'fichier'        => 'app/Services/OtpService.php',
                'ligne'          => '212-220',
                'date_correction' => now(),
                'notes_correction' => 'Corrigé : méthode getOtpInfo() supprimée.',
            ],
            [
                'code'           => 'SEC-013',
                'titre'          => 'Super-admin bypass RBAC non journalisé',
                'criticite'      => 'MOYEN',
                'statut'         => 'DETECTE',
                'categorie'      => 'Journalisation / Audit',
                'description'    => 'CheckAdminPermission middleware retourne $next($request) sans log lorsque l\'admin est super-admin. On ne peut pas distinguer en audit si une action a été effectuée grâce à une permission légitime ou via le bypass super-admin.',
                'impact'         => 'Impossible de prouver que le super-admin n\'a pas accédé à des ressources protégées. Risque de non-conformité en cas d\'audit réglementaire.',
                'recommandation' => 'Journaliser le bypass super-admin : Log::info("Super-admin bypass", [\'admin_id\' => $admin->id, \'route\' => $request->path(), \'permission\' => $permission]).',
                'fichier'        => 'app/Http/Middleware/CheckAdminPermission.php',
                'ligne'          => '30-33',
            ],
            [
                'code'           => 'SEC-014',
                'titre'          => 'Niveau de log DEBUG actif dans tous les environnements',
                'criticite'      => 'MOYEN',
                'statut'         => 'DETECTE',
                'categorie'      => 'Exposition d\'informations',
                'description'    => 'config/logging.php utilise env(\'LOG_LEVEL\', \'debug\') pour tous les canaux. En production, si LOG_LEVEL n\'est pas défini, tous les logs DEBUG sont écrits, incluant potentiellement des données sensibles, des requêtes SQL complètes, ou des informations de debug.',
                'impact'         => 'Les fichiers de log en production peuvent contenir des données utilisateurs, des tokens, des requêtes SQL avec paramètres, des traces d\'exceptions avec données sensibles.',
                'recommandation' => 'Définir LOG_LEVEL=warning dans .env de production. Vérifier que .env.production ne contient pas de valeurs de debug. Ajouter une assertion dans AppServiceProvider pour production.',
                'fichier'        => 'config/logging.php',
                'ligne'          => '28, 45, 73',
            ],
            [
                'code'           => 'SEC-015',
                'titre'          => 'Enumération de numéros de téléphone dans connexion()',
                'criticite'      => 'MOYEN',
                'statut'         => 'DETECTE',
                'categorie'      => 'Exposition d\'informations',
                'description'    => 'AuthController::connexion() retourne "Ce numéro de téléphone n\'est pas valide ou n\'existe pas" quand l\'utilisateur est introuvable. Ce message différentie clairement un numéro inexistant d\'une erreur d\'authentification.',
                'impact'         => 'Un attaquant peut énumérer quels numéros de téléphone sont enregistrés sur la plateforme. Combiné avec des données achetées, cela permet de cibler précisément les utilisateurs pour des attaques de phishing ou d\'ingénierie sociale.',
                'recommandation' => 'Retourner un message générique identique que l\'utilisateur existe ou non : "Nous avons envoyé un code de vérification si ce numéro est enregistré." Ajouter un délai artificiel constant pour normaliser les temps de réponse.',
                'fichier'        => 'app/Http/Controllers/Apiv1/AuthController.php',
                'ligne'          => '147',
            ],
            [
                'code'           => 'SEC-016',
                'titre'          => 'Index manquants sur colonnes financières critiques',
                'criticite'      => 'MOYEN',
                'statut'         => 'DETECTE',
                'categorie'      => 'Performance / Sécurité base de données',
                'description'    => 'Colonnes sans index adequat : paiement_entrants.reference_externe (UNIQUE mais lookup fréquent), cotisations.user_id et type_cotisation_id, portefeuille_epargnes.(user_id, mois_reference, annee_reference) sans contrainte UNIQUE composite.',
                'impact'         => 'Performance dégradée sur les lookups financiers. Absence de contrainte UNIQUE sur le portefeuille mensuel peut permettre la création de doublons causant des erreurs de calcul de solde.',
                'recommandation' => 'Ajouter des migrations pour créer les index manquants et la contrainte UNIQUE composite sur portefeuille_epargnes.',
                'fichier'        => 'database/migrations/*_create_paiement_entrants_table.php, *_create_cotisations_table.php, *_create_portefeuille_epargnes_table.php',
                'ligne'          => 'N/A',
            ],
            [
                'code'           => 'SEC-017',
                'titre'          => 'Race condition sur la mise à jour du portefeuille épargne',
                'criticite'      => 'MOYEN',
                'statut'         => 'DETECTE',
                'categorie'      => 'Concurrence / Données',
                'description'    => 'PortefeuilleService utilise firstOrCreate() suivi de plusieurs appels increment() séparés. Ces opérations ne sont pas atomiques. Deux paiements simultanés pour le même utilisateur et le même mois peuvent créer deux enregistrements.',
                'impact'         => 'Soldes de portefeuille incorrects, doubles enregistrements mensuels, erreurs dans les calculs de cotisation.',
                'recommandation' => 'Envelopper dans DB::transaction() avec lockForUpdate(). Utiliser updateOrCreate() avec des valeurs calculées plutôt que des increments séparés.',
                'fichier'        => 'app/Services/PortefeuilleService.php',
                'ligne'          => '20-38',
            ],

            // ──────────── FAIBLE ────────────
            [
                'code'           => 'SEC-018',
                'titre'          => 'Données PII exposées inutilement dans les exports',
                'criticite'      => 'FAIBLE',
                'statut'         => 'DETECTE',
                'categorie'      => 'Protection des données',
                'description'    => 'ExportService inclut les numéros de téléphone, emails et autres PII dans les exports CSV/Excel sans masquage. Tout administrateur ayant accès aux exports peut extraire massivement les données personnelles des utilisateurs.',
                'impact'         => 'Risque RGPD/conformité. Un admin malveillant ou un export compromis expose les données personnelles de tous les utilisateurs. Pas de traçabilité sur qui a exporté quoi.',
                'recommandation' => 'Implémenter le masquage partiel des données sensibles (ex: tél: +243 *** ** 89). Journaliser chaque export avec l\'identité de l\'admin. Restreindre l\'export à des plages de dates limitées.',
                'fichier'        => 'app/Services/ExportService.php',
                'ligne'          => 'Multiples',
            ],
            [
                'code'           => 'SEC-019',
                'titre'          => 'Domaines stateful Sanctum incluent localhost en production',
                'criticite'      => 'FAIBLE',
                'statut'         => 'DETECTE',
                'categorie'      => 'Configuration',
                'description'    => 'config/sanctum.php inclut localhost, localhost:3000, 127.0.0.1 dans les domaines stateful de base. En production, ces domaines n\'ont aucune raison d\'être autorisés et augmentent la surface d\'attaque.',
                'impact'         => 'Faible en pratique (la prod n\'est pas sur localhost), mais signale une configuration non durcis pour la production.',
                'recommandation' => 'Définir SANCTUM_STATEFUL_DOMAINS dans .env de production avec uniquement le domaine du frontend production.',
                'fichier'        => 'config/sanctum.php',
                'ligne'          => '21-26',
            ],
            [
                'code'           => 'SEC-020',
                'titre'          => 'Type de document KYC non validé avec une liste blanche',
                'criticite'      => 'FAIBLE',
                'statut'         => 'DETECTE',
                'categorie'      => 'Validation des entrées',
                'description'    => 'AjoutDocumentKYCRequest valide type_document avec [\'required\', \'string\'] uniquement. N\'importe quelle chaîne est acceptée comme type de document.',
                'impact'         => 'Données incohérentes en base. Possibilité d\'injecter des valeurs non standard pour contourner des filtres côté admin.',
                'recommandation' => 'Ajouter une règle \'in:CNI,PASSEPORT,PERMIS_CONDUIRE,CARTE_SEJOUR\' ou utiliser une règle Enum pour limiter les valeurs acceptées.',
                'fichier'        => 'app/Http/Requests/AjoutDocumentKYCRequest.php',
                'ligne'          => '27',
            ],

            // ──────────── INFO ────────────
            [
                'code'           => 'SEC-021',
                'titre'          => 'Contrainte UNIQUE composite manquante sur portefeuille_epargnes',
                'criticite'      => 'INFO',
                'statut'         => 'DETECTE',
                'categorie'      => 'Intégrité base de données',
                'description'    => 'La table portefeuille_epargnes n\'a pas de contrainte UNIQUE sur (user_id, mois_reference, annee_reference). En théorie, un utilisateur peut avoir plusieurs enregistrements pour le même mois.',
                'impact'         => 'Doublons potentiels causant des erreurs dans les calculs de cotisations mensuelles si la contrainte applicative (firstOrCreate) échoue sous concurrence.',
                'recommandation' => 'Ajouter $table->unique([\'user_id\', \'mois_reference\', \'annee_reference\']) dans une migration de correction.',
                'fichier'        => 'database/migrations/*_create_portefeuille_epargnes_table.php',
                'ligne'          => 'N/A',
            ],
            [
                'code'           => 'SEC-022',
                'titre'          => 'Absence de headers de sécurité HTTP (CSP, X-Frame-Options, etc.)',
                'criticite'      => 'INFO',
                'statut'         => 'DETECTE',
                'categorie'      => 'Headers HTTP',
                'description'    => 'L\'application ne configure pas de headers de sécurité HTTP standard : Content-Security-Policy, X-Frame-Options, X-Content-Type-Options, Referrer-Policy, Permissions-Policy.',
                'impact'         => 'Sans CSP, le risque XSS est augmenté. Sans X-Frame-Options, clickjacking possible. Sans X-Content-Type-Options, MIME sniffing possible.',
                'recommandation' => 'Ajouter un middleware SecurityHeaders dans Laravel qui injecte ces headers sur toutes les réponses. Configurer le frontend pour les headers statiques via le serveur web (Nginx/Apache).',
                'fichier'        => 'app/Http/Middleware/ (à créer)',
                'ligne'          => 'N/A',
            ],
        ];

        foreach ($vulnerabilites as $vuln) {
            AuditSecuriteVulnerabilite::create(array_merge($vuln, ['rapport_id' => $rapport->id]));
        }

        $rapport->recalculerCompteurs();
    }
}
